In [1]:
import numpy as np

In [5]:
# Return random floats in the half-open interval [0.0, 1.0). Alias for random_sample to ease forward-porting to the new random API.
np.random.random(10)

array([0.10061083, 0.25099   , 0.14657137, 0.55686841, 0.89269445,
       0.82582174, 0.69652884, 0.63201607, 0.01340495, 0.38780393])

In [12]:
np.random.seed(2)
np.random.random()

0.43599490214200376

In [17]:
# Draw samples from a uniform distribution.
# Samples are uniformly distributed over the half-open interval [low, high) (includes low, but excludes high). 
#In other words, any value within the given interval is equally likely to be drawn by uniform.
np.random.uniform(3,10)

5.312343747027119

In [19]:
np.random.uniform(3,10,10)

array([8.97782705, 6.45965786, 8.9259304 , 3.55751834, 6.53672263,
       3.45700553, 5.99685629, 3.67571641, 3.8901198 , 7.17721716])

In [20]:
np.random.uniform(3,10,10).reshape(2,5)

array([[4.582084  , 3.74861979, 4.54214345, 5.448784  , 6.27451239],
       [4.41220258, 7.48284708, 6.38148885, 6.53665704, 5.70824856]])

In [21]:
np.random.randint(1,20)

10

In [22]:
np.random.randint(1,20,5)

array([10, 15,  1, 12,  1])

In [23]:
np.random.randint(1,20,6).reshape(2,3)

array([[19,  9, 13],
       [11,  9,  3]])

In [24]:
np.random.randint(1,10,20).reshape(4,5)

array([[7, 6, 7, 7, 7],
       [4, 9, 3, 2, 5],
       [9, 2, 7, 6, 2],
       [3, 5, 8, 7, 5]])

In [25]:
a = np.random.randint(1,10,6)
a

array([6, 9, 4, 1, 1, 6])

In [27]:
a.max()

9

In [28]:
np.max(a)

9

In [29]:
np.min(a)

1

In [30]:
np.argmax(a) # Index of max

1

In [33]:
a[np.argmax(a)]

9

In [32]:
np.argmin(a)

3

In [34]:
a[np.argmin(a)]

1

In [35]:
# Problems 
a = np.random.randint(1,10,6)
a

array([8, 6, 1, 9, 7, 6])

In [39]:
# Inplace = True
a[a % 2 == 1] = -1

In [40]:
a

array([ 8,  6, -1, -1, -1,  6])

In [41]:
# np.where(condition,True value, False value)
a = np.random.randint(1,100,6)
a

array([60, 18, 16, 31, 78, 27])

In [44]:
#inplace = False
np.where(a % 2 ==1, 1000, -1000)

array([-1000, -1000, -1000,  1000, -1000,  1000])

In [43]:
a

array([60, 18, 16, 31, 78, 27])

In [45]:
out = np.where(a % 2 ==1, 1000, a)
out

array([  60,   18,   16, 1000,   78, 1000])

In [46]:
a = np.random.randint(1,50,10)
a

array([40, 44, 48, 21, 23, 37, 28,  1, 41, 29])

In [48]:
a = np.sort(a)
a

array([ 1, 21, 23, 28, 29, 37, 40, 41, 44, 48])

In [53]:
np.percentile(a,25)

24.25

In [54]:
np.percentile(a,50)

33.0

In [55]:
np.percentile(a,75)

40.75